version: '3.8'
name: django-example-prod
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/django/Dockerfile
      target: prod
    tty: true
    expose:
      - "8000"
    volumes:
      - ../static:/static
    command: sh -c "/app/entrypoint.sh"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-alpine
    expose:
      - "5432"
    env_file:
      - ../.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
  redis:
    image: "redis:7.0.11-alpine3.18"
    expose:
      - "6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ../static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db:
  web-venv:
  redis:
