version: '3.8'
name: django-example-dev
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/django/Dockerfile
      target: dev
    tty: true
    volumes:
      - ../:/app
      # exclude directory
      - web-venv:/app/.venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
  redis:
    image: "redis:7.0.11-alpine3.18"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  web-venv:
  db:
  redis: